"""add story, level, entry, source and ledger tables

Revision ID: 90509db67cff
Revises: fffccb259af4
Create Date: 2026-06-08 12:28:39.333314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90509db67cff'
down_revision: Union[str, Sequence[str], None] = 'fffccb259af4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_text', sa.Text(), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('model_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verb_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('surface_form', sa.String(length=100), nullable=False),
    sa.Column('lemma', sa.String(length=100), nullable=False),
    sa.Column('tense', sa.String(length=50), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocab_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=16), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('source_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=100), nullable=True),
    sa.Column('storage_ref', sa.String(length=500), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('author', sa.String(length=300), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('citation_text', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('title_target', sa.String(length=300), nullable=True),
    sa.Column('title_en', sa.String(length=300), nullable=True),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('story_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_level_id', sa.Integer(), nullable=True),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('iteration', sa.Integer(), nullable=False),
    sa.Column('raw_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('critic_results', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_level_id'], ['story_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grammar_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_level_id', sa.Integer(), nullable=False),
    sa.Column('surface_form', sa.String(length=100), nullable=False),
    sa.Column('lemma', sa.String(length=100), nullable=False),
    sa.Column('tense', sa.String(length=50), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['story_level_id'], ['story_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verb_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_level_id', sa.Integer(), nullable=False),
    sa.Column('surface_form', sa.String(length=100), nullable=False),
    sa.Column('lemma', sa.String(length=100), nullable=False),
    sa.Column('tense', sa.String(length=50), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=False),
    sa.Column('example_sentence_target', sa.Text(), nullable=False),
    sa.Column('example_sentence_en', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_level_id'], ['story_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vocabulary_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('story_level_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('translation', sa.String(length=200), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['story_level_id'], ['story_levels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vocabulary_entries')
    op.drop_table('verb_entries')
    op.drop_table('grammar_entries')
    op.drop_table('generation_runs')
    op.drop_table('story_levels')
    op.drop_table('sources')
    op.drop_table('source_documents')
    op.drop_table('vocab_ledger')
    op.drop_table('verb_ledger')
    op.drop_table('stories')
    # ### end Alembic commands ###
