"""add brief_prompt to stories

Revision ID: d895babce9e7
Revises: 498964ba1582
Create Date: 2026-06-09 10:28:54.145514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd895babce9e7'
down_revision: Union[str, Sequence[str], None] = '498964ba1582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('brief_prompt', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'brief_prompt')
    # ### end Alembic commands ###
