import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import { QueryClient } from '@tanstack/react-query'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { PersistQueryClientProvider } from '@tanstack/react-query-persist-client'
import { createSyncStoragePersister } from '@tanstack/query-sync-storage-persister'
import { RouterProvider, createRouter } from '@tanstack/react-router'
import './index.css'

// Generated by the TanStack Router Vite plugin from files in src/routes/.
import { routeTree } from './routeTree.gen'

const ONE_DAY = 1000 * 60 * 60 * 24

const queryClient = new QueryClient({
  defaultOptions: {
    // gcTime must outlive the persisted maxAge, or restored entries are dropped
    // immediately. Keep cached queries around for a day.
    queries: { gcTime: ONE_DAY },
  },
})

// Persists the whole query cache to localStorage so results survive a full page
// reload (the in-memory cache alone is wiped on reload).
const persister = createSyncStoragePersister({ storage: window.localStorage })

const router = createRouter({ routeTree })

// Make router types available globally for type-safe links/navigation.
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router
  }
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <PersistQueryClientProvider
      client={queryClient}
      persistOptions={{ persister, maxAge: ONE_DAY }}
    >
      <RouterProvider router={router} />
      <ReactQueryDevtools initialIsOpen={false} />
    </PersistQueryClientProvider>
  </StrictMode>,
)
